repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: local
    hooks:
    - id: test_flake8
      name: Run flake8
      entry: python tests/test_flake8.py $(git diff --cached --name-only --diff-filter=ACM -z | xargs -0)
      language: system
      types: [python]
